### ISSUE TITLE
services.worker.environment, v1.8.0 SECRET_KEY_BASE missing

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_ELN#1622]
- I am an ELNer
- I am a system/ELN admin

# Expected Behavior

Run:

```
wget https://raw.githubusercontent.com/Chemotion/ChemCLI/main/payload/docker-compose.yml
```
Modify the docker-compose.yml as described in the [documentation](https://www.chemotion.net/docs/eln/install_configure/manual_install), then

```
docker compose up --no-start && docker compose up -d
```

All containers should be running.

# Current Behavior

Snipped of docker-compose.yml obtained with the command above:

```
version: "3.9"
services:
[...]
  worker:
    image: ptrxyz/chemotion:eln-1.8.0
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=worker
    depends_on:
      - db
[...]

  eln:
    image: ptrxyz/chemotion:eln-1.8.0
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=eln
      - SECRET_KEY_BASE=pleasechangeme
    depends_on:
      - db
 [...]
networks:
  chemotion:
```

SECRET_KEY_BASE missing under services.worker.environment causes the worker to restart and restart over and over again. SECRET_KEY_BASE was present in services.worker.environment in the docker-compose.yml template provided for v1.6.0.

# Possible solution 

Template may be changed to:

```
version: "3.9"
services:
[...]
  worker:
    image: ptrxyz/chemotion:eln-1.8.0
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=worker
      - SECRET_KEY_BASE=pleasechangeme
    depends_on:
      - db
[...]

  eln:
    image: ptrxyz/chemotion:eln-1.8.0
    restart: unless-stopped
    environment:
      - CONFIG_ROLE=eln
      - SECRET_KEY_BASE=pleasechangeme
    depends_on:
      - db
 [...]
networks:
  chemotion:
```

## Context

 - OS:  OpenSUSE Tumbleweed
 - ELN version, or branch, or commit: v1.8.0
 
Best,
Tillmann
