### ISSUE TITLE
UI: harmonize fonts

### ISSUE THREAD

**Issue by ptrxyz** [ComPlat/chemotion_ELN#613]
# Description
I found that we do currently not have a consistent font scheme throughout the UI. Sometimes we default to sans-serif, otherwise we prefer Arial over Helvetica etc. In order to harmonize the look and feel for Chemotion, I suggest to have system default fonts followed by a single, uniform (sans) font for all the UI on all platforms, followed by some system-specific, "catch-most" fonts to support CJK and Emoji Characters.

Considering different licenses and looks, the Roboto font families might be a good fit (Apache 2.0, they can be used freely in products & projects - print or digital, commercial or otherwise). In addition, Roboto has a plain & simple appearance and is widely used having people perceive it as familiar. It comes in many styles and several variants, such as a thin to bold black and narrow or monospace. Considering technical aspects, Roboto is available in several formats, including `.woff` and `.woff2` and could thus easily be included via the Google Fonts CDN (to make increase the chance of cache hits) or shipped locally (for installations not having access to the web). The fonts do have a installation package for the Ubuntu platform and could easily be used on the backend for rendering static assets and graphics. In addition a wide range of latin and non-lating glyphs are supported which might help with other languages such as cyrillic or greek.

For the reasons above I suggest to use this in our `application.scss.erb`:

```scss
body, html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```
preferably in conjunction with loading a default font in the main application similar to this:
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed|WhatEverWeNeedCouldGoHere">
```

To increase consistency even further, I would suggest to carry this over to Chemotion Repo as well.
